services:
  scoreboard-server:
    build: ./scoreboard-server
    environment:
      - "WEBHOOK_SECRET=cde314dda67268f78747458e1a9b9677905ea5ce5d02cc1a19374c091d7db4a7"
    restart: always
    networks:
      default:
      internal:
  scoreboard:
    build: ./scoreboard
    restart: always
    volumes:
      - .:/opt/CTFd:ro
    environment:
      - CTFD_API_URL=http://ctfd:8000/api/v1
      - CTFD_API_KEY=ctfd_c034c072626ada9c0cb2cfdb1380f39f98997fd925d0e96bb7186494f00eeeb8
    networks:
        default:
        internal:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - CS2_WEBHOOK_URL=http://scoreboard-server:3000/api/webhook
      - CS2_WEBHOOK_SECRET=cde314dda67268f78747458e1a9b9677905ea5ce5d02cc1a19374c091d7db4a7
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ctfd
      - scoreboard
      - scoreboard-server

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
